name: Newman Collection Runner
on:
  workflow_call:
    inputs:
      collection:
        required: true
        type: string
      environment: 
        required: true
        type: string

jobs:
  test:
    name: 'API Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: matt-ball/newman-action@master
      name: 'Newman Collection Runner'
      with:
        collection: ${{ inputs.collection }}
        environment: ${{ inputs.environment }}
        reporters: '["cli"]'
        delayRequest: 0
        iterationCount: 2
