name: Newman Collection Runner
on:
  workflow_call:
    inputs:
      collection:
        required: true
        type: string
      environment: 
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  test:
    name: 'API Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set Azure URL
      run: |
        bash smoketest.sh -u ${{ inputs.url }}

    - name: Run Smoke Test
      run: |
        bash smoketest.sh -e azure

